name: Test MikroTik Downloads (Latest)

on:
  workflow_dispatch: # تشغيل يدوي من GitHub Actions

jobs:
  download-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest RouterOS 7 version
        run: |
          VERSION=$(curl -s https://upgrade.mikrotik.com/routeros/LATEST.7)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Latest version is $VERSION"

      - name: Create artifacts folder
        run: mkdir -p artifacts

      - name: Download netinstall
        run: |
          URL="https://download.mikrotik.com/routeros/${VERSION}/netinstall-${VERSION}.zip"
          wget --spider "$URL" && wget -nv -O artifacts/netinstall-${VERSION}.zip "$URL"

      - name: Download install-image
        run: |
          URL="https://download.mikrotik.com/routeros/${VERSION}/install-image-${VERSION}.zip"
          wget --spider "$URL" && wget -nv -O artifacts/install-image-${VERSION}.zip "$URL"

      - name: Download mmips
        run: |
          URL="https://download.mikrotik.com/routeros/${VERSION}/routeros-${VERSION}-mmips.npk"
          wget --spider "$URL" && wget -nv -O artifacts/routeros-${VERSION}-mmips.npk "$URL"

      - name: Download tile
        run: |
          URL="https://download.mikrotik.com/routeros/${VERSION}/all_packages-tile-${VERSION}.zip"
          wget --spider "$URL" && wget -nv -O artifacts/all_packages-tile-${VERSION}.zip "$URL"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mikrotik-${{ env.VERSION }}
          path: artifacts/
