name: Test Mikrotik RouterOS Files

on:
  workflow_dispatch:

jobs:
  download-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest RouterOS 7 version
        run: |
          RAW=$(curl -s https://upgrade.mikrotik.com/routeros/LATEST.7)
          VERSION=$(echo "$RAW" | awk '{print $1}')   # ناخد أول كلمة فقط
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Latest version is $VERSION"

      - name: Download Netinstall
        run: |
          URL="https://download.mikrotik.com/routeros/${VERSION}/netinstall-${VERSION}.zip"
          echo "Downloading: $URL"
          wget -nv -O netinstall-${VERSION}.zip "$URL"

      - name: Download ISO
        run: |
          URL="https://download.mikrotik.com/routeros/${VERSION}/mikrotik-${VERSION}.iso"
          echo "Downloading: $URL"
          wget -nv -O mikrotik-${VERSION}.iso "$URL"

      - name: Download Install-Image
        run: |
          URL="https://download.mikrotik.com/routeros/${VERSION}/install-image-${VERSION}.zip"
          echo "Downloading: $URL"
          wget -nv -O install-image-${VERSION}.zip "$URL"

      - name: Download MMIPS
        run: |
          URL="https://download.mikrotik.com/routeros/${VERSION}/routeros-${VERSION}-mmips.npk"
          echo "Downloading: $URL"
          wget -nv -O routeros-${VERSION}-mmips.npk "$URL"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mikrotik-files
          path: |
            netinstall-*.zip
            mikrotik-*.iso
            install-image-*.zip
            routeros-*-mmips.npk
          retention-days: 3
