VERSION="7.19.6"

# netinstall
URL_NETINSTALL="https://download.mikrotik.com/routeros/$VERSION/netinstall-$VERSION.zip"
wget --spider "$URL_NETINSTALL" && wget -nv -O "netinstall-$VERSION.zip" "$URL_NETINSTALL"

# install-image
URL_INSTALL="https://download.mikrotik.com/routeros/$VERSION/install-image-$VERSION.zip"
wget --spider "$URL_INSTALL" && wget -nv -O "install-image-$VERSION.zip" "$URL_INSTALL"

# mmips
URL_MMIPS="https://download.mikrotik.com/routeros/$VERSION/routeros-$VERSION-mmips.npk"
wget --spider "$URL_MMIPS" && wget -nv -O "routeros-$VERSION-mmips.npk" "$URL_MMIPS"

# tile
URL_TILE="https://download.mikrotik.com/routeros/$VERSION/all_packages-tile-$VERSION.zip"
wget --spider "$URL_TILE" && wget -nv -O "all_packages-tile-$VERSION.zip" "$URL_TILE"
